apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-web
  labels:
    {{- include "provider-web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "provider-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "provider-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: provider-web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: http
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
