apiVersion: v1
kind: Service
metadata:
  name: provider-web
  labels:
    {{- include "provider-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "provider-web.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
