// Generated from config/ontology/graph_seeds.yaml

// Adverse outcomes
MERGE (:AdverseOutcome {code: "DE", description: "Death"});
MERGE (:AdverseOutcome {code: "LT", description: "Life-Threatening"});
MERGE (:AdverseOutcome {code: "HO", description: "Hospitalization - Initial or Prolonged"});
MERGE (:AdverseOutcome {code: "DS", description: "Disability"});
MERGE (:AdverseOutcome {code: "CA", description: "Congenital Anomaly"});
MERGE (:AdverseOutcome {code: "OT", description: "Other Serious (Important Medical Events)"});

// Condition seeds
MERGE (:Condition {name: "Hyperkalemia"});
MERGE (:Condition {name: "Hyperglycemia"});
MERGE (:Condition {name: "Diabetes Mellitus"});
MERGE (:Condition {name: "Chronic Kidney Disease"});
MERGE (:Condition {name: "Acute Myocardial Infarction"});
MERGE (:Condition {name: "Anemia"});
MERGE (:Condition {name: "Hyperlipidemia"});
MERGE (:Condition {name: "Hypothyroidism"});
MERGE (:Condition {name: "Hyperthyroidism"});
MERGE (:Condition {name: "Hyponatremia"});
MERGE (:Condition {name: "Hypernatremia"});
MERGE (:Condition {name: "Infection"});
MERGE (:Condition {name: "Anticoagulation Concern"});
MERGE (:Condition {name: "Hypertension"});
MERGE (:Condition {name: "Heart Failure"});
MERGE (:Condition {name: "Asthma"});
MERGE (:Condition {name: "Atrial Fibrillation"});
MERGE (:Condition {name: "Hypoglycemia"});
MERGE (:Condition {name: "COPD"});
MERGE (:Condition {name: "Pancreatitis"});

// Symptom seeds
MERGE (:Symptom {name: "palpitations"});
MERGE (:Symptom {name: "confusion"});
MERGE (:Symptom {name: "cough"});
MERGE (:Symptom {name: "dizziness"});
MERGE (:Symptom {name: "fatigue"});
MERGE (:Symptom {name: "leg cramps"});
MERGE (:Symptom {name: "swelling"});
MERGE (:Symptom {name: "shortness of breath"});
MERGE (:Symptom {name: "nausea"});
MERGE (:Symptom {name: "vomiting"});
MERGE (:Symptom {name: "chest pain"});
MERGE (:Symptom {name: "weight loss"});
MERGE (:Symptom {name: "headache"});
MERGE (:Symptom {name: "blurred vision"});
MERGE (:Symptom {name: "night sweats"});

// Medication metadata
MATCH (m:Medication {name: "Warfarin"}) SET m.activeIngredient = "Warfarin sodium", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Metformin"}) SET m.activeIngredient = "Metformin hydrochloride", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Atorvastatin"}) SET m.activeIngredient = "Atorvastatin calcium", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Levothyroxine"}) SET m.activeIngredient = "Levothyroxine sodium", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Sertraline"}) SET m.activeIngredient = "Sertraline hydrochloride", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Metoprolol"}) SET m.activeIngredient = "Metoprolol tartrate", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Lisinopril"}) SET m.activeIngredient = "Lisinopril", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Amlodipine"}) SET m.activeIngredient = "Amlodipine besylate", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Omeprazole"}) SET m.activeIngredient = "Omeprazole", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Clopidogrel"}) SET m.activeIngredient = "Clopidogrel bisulfate", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Furosemide"}) SET m.activeIngredient = "Furosemide", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Gabapentin"}) SET m.activeIngredient = "Gabapentin", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Losartan"}) SET m.activeIngredient = "Losartan potassium", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Hydrochlorothiazide"}) SET m.activeIngredient = "Hydrochlorothiazide", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Spironolactone"}) SET m.activeIngredient = "Spironolactone", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Azithromycin"}) SET m.activeIngredient = "Azithromycin", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Albuterol"}) SET m.activeIngredient = "Albuterol sulfate", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Prednisone"}) SET m.activeIngredient = "Prednisone", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Morphine"}) SET m.activeIngredient = "Morphine sulfate", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Heparin"}) SET m.activeIngredient = "Heparin sodium", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Insulin Glargine"}) SET m.activeIngredient = "Insulin glargine", m.isValidatedTradeNameUsed = true;
MATCH (m:Medication {name: "Vancomycin"}) SET m.activeIngredient = "Vancomycin hydrochloride", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Dexamethasone"}) SET m.activeIngredient = "Dexamethasone", m.isValidatedTradeNameUsed = false;
MATCH (m:Medication {name: "Amoxicillin"}) SET m.activeIngredient = "Amoxicillin trihydrate", m.isValidatedTradeNameUsed = false;

// Drug interactions
MERGE (:Medication {name: "Warfarin"});
MERGE (:Medication {name: "Azithromycin"});
MATCH (from:Medication {name: "Warfarin"}) MATCH (to:Medication {name: "Azithromycin"}) MERGE (from)-[:INTERACTS_WITH {risk: "bleeding_risk", severity: "high", mechanism: "CYP3A4_inhibition_increases_warfarin_exposure"}]->(to);
MERGE (:Medication {name: "Warfarin"});
MERGE (:Medication {name: "Aspirin"});
MATCH (from:Medication {name: "Warfarin"}) MATCH (to:Medication {name: "Aspirin"}) MERGE (from)-[:INTERACTS_WITH {risk: "bleeding_risk", severity: "high", mechanism: "additive_anticoagulation_and_antiplatelet"}]->(to);
MERGE (:Medication {name: "Lisinopril"});
MERGE (:Medication {name: "Spironolactone"});
MATCH (from:Medication {name: "Lisinopril"}) MATCH (to:Medication {name: "Spironolactone"}) MERGE (from)-[:INTERACTS_WITH {risk: "hyperkalemia_risk", severity: "moderate", mechanism: "dual_potassium_sparing_ACE_inhibitor_plus_K_sparing_diuretic"}]->(to);
MERGE (:Medication {name: "Albuterol"});
MERGE (:Medication {name: "Metoprolol"});
MATCH (from:Medication {name: "Albuterol"}) MATCH (to:Medication {name: "Metoprolol"}) MERGE (from)-[:INTERACTS_WITH {risk: "bronchospasm_risk", severity: "moderate", mechanism: "pharmacological_antagonism_beta2_agonist_vs_beta_blocker"}]->(to);
MERGE (:Medication {name: "Metformin"});
MERGE (:Medication {name: "Vancomycin"});
MATCH (from:Medication {name: "Metformin"}) MATCH (to:Medication {name: "Vancomycin"}) MERGE (from)-[:INTERACTS_WITH {risk: "nephrotoxicity_risk", severity: "moderate", mechanism: "renal_competition_reduces_metformin_clearance"}]->(to);
MERGE (:Medication {name: "Warfarin"});
MERGE (:Medication {name: "Fluconazole"});
MATCH (from:Medication {name: "Warfarin"}) MATCH (to:Medication {name: "Fluconazole"}) MERGE (from)-[:INTERACTS_WITH {risk: "bleeding_risk", severity: "high", mechanism: "CYP2C9_inhibition_markedly_raises_warfarin_INR"}]->(to);
MERGE (:Medication {name: "Aspirin"});
MERGE (:Medication {name: "Clopidogrel"});
MATCH (from:Medication {name: "Aspirin"}) MATCH (to:Medication {name: "Clopidogrel"}) MERGE (from)-[:INTERACTS_WITH {risk: "bleeding_risk", severity: "high", mechanism: "dual_antiplatelet_aggregation"}]->(to);
MERGE (:Medication {name: "Atorvastatin"});
MERGE (:Medication {name: "Azithromycin"});
MATCH (from:Medication {name: "Atorvastatin"}) MATCH (to:Medication {name: "Azithromycin"}) MERGE (from)-[:INTERACTS_WITH {risk: "myopathy_risk", severity: "moderate", mechanism: "CYP3A4_inhibition_raises_statin_levels"}]->(to);
MERGE (:Medication {name: "Losartan"});
MERGE (:Medication {name: "Spironolactone"});
MATCH (from:Medication {name: "Losartan"}) MATCH (to:Medication {name: "Spironolactone"}) MERGE (from)-[:INTERACTS_WITH {risk: "hyperkalemia_risk", severity: "moderate", mechanism: "dual_RAAS_blockade"}]->(to);
MERGE (:Medication {name: "Furosemide"});
MERGE (:Medication {name: "Vancomycin"});
MATCH (from:Medication {name: "Furosemide"}) MATCH (to:Medication {name: "Vancomycin"}) MERGE (from)-[:INTERACTS_WITH {risk: "nephrotoxicity_risk", severity: "high", mechanism: "synergistic_renal_toxicity"}]->(to);
MERGE (:Medication {name: "Metoprolol"});
MERGE (:Medication {name: "Insulin Glargine"});
MATCH (from:Medication {name: "Metoprolol"}) MATCH (to:Medication {name: "Insulin Glargine"}) MERGE (from)-[:INTERACTS_WITH {risk: "hypoglycemia_masking", severity: "moderate", mechanism: "beta_blockade_masks_tachycardia_warning_sign"}]->(to);
MERGE (:Medication {name: "Dexamethasone"});
MERGE (:Medication {name: "Insulin Glargine"});
MATCH (from:Medication {name: "Dexamethasone"}) MATCH (to:Medication {name: "Insulin Glargine"}) MERGE (from)-[:INTERACTS_WITH {risk: "hyperglycemia_risk", severity: "moderate", mechanism: "glucocorticoid_induced_insulin_resistance"}]->(to);
MERGE (:Medication {name: "Clopidogrel"});
MERGE (:Medication {name: "Omeprazole"});
MATCH (from:Medication {name: "Clopidogrel"}) MATCH (to:Medication {name: "Omeprazole"}) MERGE (from)-[:INTERACTS_WITH {risk: "reduced_antiplatelet_efficacy", severity: "moderate", mechanism: "CYP2C19_inhibition_reduces_clopidogrel_activation"}]->(to);
MERGE (:Medication {name: "Hydrochlorothiazide"});
MERGE (:Medication {name: "Furosemide"});
MATCH (from:Medication {name: "Hydrochlorothiazide"}) MATCH (to:Medication {name: "Furosemide"}) MERGE (from)-[:INTERACTS_WITH {risk: "electrolyte_depletion", severity: "moderate", mechanism: "additive_diuresis_hypokalemia_hyponatremia"}]->(to);
MERGE (:Medication {name: "Morphine"});
MERGE (:Medication {name: "Gabapentin"});
MATCH (from:Medication {name: "Morphine"}) MATCH (to:Medication {name: "Gabapentin"}) MERGE (from)-[:INTERACTS_WITH {risk: "respiratory_depression", severity: "high", mechanism: "additive_CNS_depression"}]->(to);

// Expanded drug interactions
MERGE (:Medication {name: "Warfarin"});
MERGE (:Medication {name: "Ibuprofen"});
MATCH (from:Medication {name: "Warfarin"}) MATCH (to:Medication {name: "Ibuprofen"}) MERGE (from)-[:INTERACTS_WITH {risk: "bleeding_risk", severity: "high", mechanism: "NSAID_inhibits_platelet_aggregation_and_displaces_warfarin"}]->(to);
MERGE (:Medication {name: "Warfarin"});
MERGE (:Medication {name: "Heparin"});
MATCH (from:Medication {name: "Warfarin"}) MATCH (to:Medication {name: "Heparin"}) MERGE (from)-[:INTERACTS_WITH {risk: "bleeding_risk", severity: "high", mechanism: "dual_anticoagulation"}]->(to);
MERGE (:Medication {name: "Warfarin"});
MERGE (:Medication {name: "Enoxaparin"});
MATCH (from:Medication {name: "Warfarin"}) MATCH (to:Medication {name: "Enoxaparin"}) MERGE (from)-[:INTERACTS_WITH {risk: "bleeding_risk", severity: "high", mechanism: "dual_anticoagulation_LMWH_plus_VKA"}]->(to);
MERGE (:Medication {name: "Warfarin"});
MERGE (:Medication {name: "Amoxicillin"});
MATCH (from:Medication {name: "Warfarin"}) MATCH (to:Medication {name: "Amoxicillin"}) MERGE (from)-[:INTERACTS_WITH {risk: "bleeding_risk", severity: "moderate", mechanism: "gut_flora_disruption_increases_INR"}]->(to);
MERGE (:Medication {name: "Sertraline"});
MERGE (:Medication {name: "Morphine"});
MATCH (from:Medication {name: "Sertraline"}) MATCH (to:Medication {name: "Morphine"}) MERGE (from)-[:INTERACTS_WITH {risk: "serotonin_syndrome", severity: "high", mechanism: "SSRI_plus_opioid_serotonergic_synergy"}]->(to);
MERGE (:Medication {name: "Sertraline"});
MERGE (:Medication {name: "Aspirin"});
MATCH (from:Medication {name: "Sertraline"}) MATCH (to:Medication {name: "Aspirin"}) MERGE (from)-[:INTERACTS_WITH {risk: "GI_bleeding_risk", severity: "moderate", mechanism: "SSRI_impairs_platelet_serotonin_uptake"}]->(to);
MERGE (:Medication {name: "Sertraline"});
MERGE (:Medication {name: "Ibuprofen"});
MATCH (from:Medication {name: "Sertraline"}) MATCH (to:Medication {name: "Ibuprofen"}) MERGE (from)-[:INTERACTS_WITH {risk: "GI_bleeding_risk", severity: "moderate", mechanism: "SSRI_plus_NSAID_additive_bleeding"}]->(to);
MERGE (:Medication {name: "Lisinopril"});
MERGE (:Medication {name: "Losartan"});
MATCH (from:Medication {name: "Lisinopril"}) MATCH (to:Medication {name: "Losartan"}) MERGE (from)-[:INTERACTS_WITH {risk: "hyperkalemia_risk", severity: "high", mechanism: "dual_RAAS_blockade_ACEi_plus_ARB"}]->(to);
MERGE (:Medication {name: "Digoxin"});
MERGE (:Medication {name: "Amiodarone"});
MATCH (from:Medication {name: "Digoxin"}) MATCH (to:Medication {name: "Amiodarone"}) MERGE (from)-[:INTERACTS_WITH {risk: "digoxin_toxicity", severity: "high", mechanism: "amiodarone_reduces_digoxin_clearance"}]->(to);
MERGE (:Medication {name: "Digoxin"});
MERGE (:Medication {name: "Furosemide"});
MATCH (from:Medication {name: "Digoxin"}) MATCH (to:Medication {name: "Furosemide"}) MERGE (from)-[:INTERACTS_WITH {risk: "digoxin_toxicity", severity: "moderate", mechanism: "hypokalemia_increases_digoxin_sensitivity"}]->(to);
MERGE (:Medication {name: "Digoxin"});
MERGE (:Medication {name: "Spironolactone"});
MATCH (from:Medication {name: "Digoxin"}) MATCH (to:Medication {name: "Spironolactone"}) MERGE (from)-[:INTERACTS_WITH {risk: "digoxin_toxicity", severity: "moderate", mechanism: "spironolactone_reduces_digoxin_clearance"}]->(to);
MERGE (:Medication {name: "Apixaban"});
MERGE (:Medication {name: "Aspirin"});
MATCH (from:Medication {name: "Apixaban"}) MATCH (to:Medication {name: "Aspirin"}) MERGE (from)-[:INTERACTS_WITH {risk: "bleeding_risk", severity: "high", mechanism: "DOAC_plus_antiplatelet_additive_bleeding"}]->(to);
MERGE (:Medication {name: "Rivaroxaban"});
MERGE (:Medication {name: "Aspirin"});
MATCH (from:Medication {name: "Rivaroxaban"}) MATCH (to:Medication {name: "Aspirin"}) MERGE (from)-[:INTERACTS_WITH {risk: "bleeding_risk", severity: "high", mechanism: "DOAC_plus_antiplatelet_additive_bleeding"}]->(to);
MERGE (:Medication {name: "Enoxaparin"});
MERGE (:Medication {name: "Aspirin"});
MATCH (from:Medication {name: "Enoxaparin"}) MATCH (to:Medication {name: "Aspirin"}) MERGE (from)-[:INTERACTS_WITH {risk: "bleeding_risk", severity: "high", mechanism: "LMWH_plus_antiplatelet"}]->(to);
MERGE (:Medication {name: "Prednisone"});
MERGE (:Medication {name: "Ibuprofen"});
MATCH (from:Medication {name: "Prednisone"}) MATCH (to:Medication {name: "Ibuprofen"}) MERGE (from)-[:INTERACTS_WITH {risk: "GI_ulceration_risk", severity: "high", mechanism: "corticosteroid_plus_NSAID_mucosal_injury"}]->(to);
MERGE (:Medication {name: "Prednisone"});
MERGE (:Medication {name: "Insulin Glargine"});
MATCH (from:Medication {name: "Prednisone"}) MATCH (to:Medication {name: "Insulin Glargine"}) MERGE (from)-[:INTERACTS_WITH {risk: "hyperglycemia_risk", severity: "moderate", mechanism: "glucocorticoid_induced_insulin_resistance"}]->(to);
MERGE (:Medication {name: "Metoprolol"});
MERGE (:Medication {name: "Diltiazem"});
MATCH (from:Medication {name: "Metoprolol"}) MATCH (to:Medication {name: "Diltiazem"}) MERGE (from)-[:INTERACTS_WITH {risk: "severe_bradycardia", severity: "high", mechanism: "additive_AV_node_blockade"}]->(to);
MERGE (:Medication {name: "Metoprolol"});
MERGE (:Medication {name: "Carvedilol"});
MATCH (from:Medication {name: "Metoprolol"}) MATCH (to:Medication {name: "Carvedilol"}) MERGE (from)-[:INTERACTS_WITH {risk: "severe_bradycardia", severity: "high", mechanism: "duplicate_beta_blockade"}]->(to);
MERGE (:Medication {name: "Sacubitril-Valsartan"});
MERGE (:Medication {name: "Lisinopril"});
MATCH (from:Medication {name: "Sacubitril-Valsartan"}) MATCH (to:Medication {name: "Lisinopril"}) MERGE (from)-[:INTERACTS_WITH {risk: "angioedema_risk", severity: "high", mechanism: "ARNI_plus_ACEi_contraindicated_within_36h"}]->(to);
MERGE (:Medication {name: "Empagliflozin"});
MERGE (:Medication {name: "Furosemide"});
MATCH (from:Medication {name: "Empagliflozin"}) MATCH (to:Medication {name: "Furosemide"}) MERGE (from)-[:INTERACTS_WITH {risk: "dehydration_hypotension", severity: "moderate", mechanism: "SGLT2i_plus_loop_diuretic_volume_depletion"}]->(to);
MERGE (:Medication {name: "Ceftriaxone"});
MERGE (:Medication {name: "Furosemide"});
MATCH (from:Medication {name: "Ceftriaxone"}) MATCH (to:Medication {name: "Furosemide"}) MERGE (from)-[:INTERACTS_WITH {risk: "nephrotoxicity_risk", severity: "moderate", mechanism: "synergistic_renal_tubular_toxicity"}]->(to);
MERGE (:Medication {name: "Linezolid"});
MERGE (:Medication {name: "Sertraline"});
MATCH (from:Medication {name: "Linezolid"}) MATCH (to:Medication {name: "Sertraline"}) MERGE (from)-[:INTERACTS_WITH {risk: "serotonin_syndrome", severity: "high", mechanism: "MAOi_activity_plus_SSRI"}]->(to);
MERGE (:Medication {name: "Ondansetron"});
MERGE (:Medication {name: "Azithromycin"});
MATCH (from:Medication {name: "Ondansetron"}) MATCH (to:Medication {name: "Azithromycin"}) MERGE (from)-[:INTERACTS_WITH {risk: "QT_prolongation", severity: "high", mechanism: "additive_QT_prolonging_effect"}]->(to);
MERGE (:Medication {name: "Nitroglycerin"});
MERGE (:Medication {name: "Amlodipine"});
MATCH (from:Medication {name: "Nitroglycerin"}) MATCH (to:Medication {name: "Amlodipine"}) MERGE (from)-[:INTERACTS_WITH {risk: "severe_hypotension", severity: "high", mechanism: "additive_vasodilation"}]->(to);
MERGE (:Medication {name: "Acetaminophen"});
MERGE (:Medication {name: "Warfarin"});
MATCH (from:Medication {name: "Acetaminophen"}) MATCH (to:Medication {name: "Warfarin"}) MERGE (from)-[:INTERACTS_WITH {risk: "INR_elevation", severity: "moderate", mechanism: "acetaminophen_potentiates_warfarin_at_high_doses"}]->(to);

// Expanded contraindications
MERGE (:Medication {name: "Ibuprofen"});
MERGE (:Condition {name: "Chronic Kidney Disease"});
MATCH (m:Medication {name: "Ibuprofen"}) MATCH (c:Condition {name: "Chronic Kidney Disease"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "NSAID_nephrotoxicity", severity: "high"}]->(c);
MERGE (:Medication {name: "Ibuprofen"});
MERGE (:Condition {name: "Heart Failure"});
MATCH (m:Medication {name: "Ibuprofen"}) MATCH (c:Condition {name: "Heart Failure"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "NSAID_fluid_retention_worsens_HF", severity: "high"}]->(c);
MERGE (:Medication {name: "Digoxin"});
MERGE (:Condition {name: "Hyperkalemia"});
MATCH (m:Medication {name: "Digoxin"}) MATCH (c:Condition {name: "Hyperkalemia"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "hyperkalemia_increases_digoxin_toxicity", severity: "high"}]->(c);
MERGE (:Medication {name: "Empagliflozin"});
MERGE (:Condition {name: "Chronic Kidney Disease"});
MATCH (m:Medication {name: "Empagliflozin"}) MATCH (c:Condition {name: "Chronic Kidney Disease"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "eGFR_dependent_efficacy_reduced_below_20", severity: "moderate"}]->(c);
MERGE (:Medication {name: "Apixaban"});
MERGE (:Condition {name: "Anemia"});
MATCH (m:Medication {name: "Apixaban"}) MATCH (c:Condition {name: "Anemia"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "DOAC_bleeding_risk_in_anemia", severity: "high"}]->(c);
MERGE (:Medication {name: "Enoxaparin"});
MERGE (:Condition {name: "Chronic Kidney Disease"});
MATCH (m:Medication {name: "Enoxaparin"}) MATCH (c:Condition {name: "Chronic Kidney Disease"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "LMWH_accumulation_in_renal_impairment", severity: "high"}]->(c);

// Contraindications
MERGE (:Medication {name: "Warfarin"});
MERGE (:Condition {name: "Anemia"});
MATCH (m:Medication {name: "Warfarin"}) MATCH (c:Condition {name: "Anemia"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "increased_bleeding_risk", severity: "high"}]->(c);
MERGE (:Medication {name: "Lisinopril"});
MERGE (:Condition {name: "Hyperkalemia"});
MATCH (m:Medication {name: "Lisinopril"}) MATCH (c:Condition {name: "Hyperkalemia"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "worsens_hyperkalemia", severity: "high"}]->(c);
MERGE (:Medication {name: "Metformin"});
MERGE (:Condition {name: "Chronic Kidney Disease"});
MATCH (m:Medication {name: "Metformin"}) MATCH (c:Condition {name: "Chronic Kidney Disease"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "lactic_acidosis_risk", severity: "high"}]->(c);
MERGE (:Medication {name: "Spironolactone"});
MERGE (:Condition {name: "Hyperkalemia"});
MATCH (m:Medication {name: "Spironolactone"}) MATCH (c:Condition {name: "Hyperkalemia"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "worsens_hyperkalemia", severity: "high"}]->(c);
MERGE (:Medication {name: "Albuterol"});
MERGE (:Condition {name: "Heart Failure"});
MATCH (m:Medication {name: "Albuterol"}) MATCH (c:Condition {name: "Heart Failure"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "tachycardia_risk", severity: "moderate"}]->(c);
MERGE (:Medication {name: "Vancomycin"});
MERGE (:Condition {name: "Chronic Kidney Disease"});
MATCH (m:Medication {name: "Vancomycin"}) MATCH (c:Condition {name: "Chronic Kidney Disease"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "nephrotoxicity", severity: "high"}]->(c);
MERGE (:Medication {name: "Heparin"});
MERGE (:Condition {name: "Anemia"});
MATCH (m:Medication {name: "Heparin"}) MATCH (c:Condition {name: "Anemia"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "increased_bleeding_risk", severity: "high"}]->(c);
MERGE (:Medication {name: "Clopidogrel"});
MERGE (:Condition {name: "Anemia"});
MATCH (m:Medication {name: "Clopidogrel"}) MATCH (c:Condition {name: "Anemia"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "increased_bleeding_risk", severity: "high"}]->(c);
MERGE (:Medication {name: "Prednisone"});
MERGE (:Condition {name: "Diabetes Mellitus"});
MATCH (m:Medication {name: "Prednisone"}) MATCH (c:Condition {name: "Diabetes Mellitus"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "steroid_induced_hyperglycemia", severity: "moderate"}]->(c);
MERGE (:Medication {name: "Dexamethasone"});
MERGE (:Condition {name: "Diabetes Mellitus"});
MATCH (m:Medication {name: "Dexamethasone"}) MATCH (c:Condition {name: "Diabetes Mellitus"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "glucocorticoid_raises_blood_glucose", severity: "moderate"}]->(c);
MERGE (:Medication {name: "Hydrochlorothiazide"});
MERGE (:Condition {name: "Hyponatremia"});
MATCH (m:Medication {name: "Hydrochlorothiazide"}) MATCH (c:Condition {name: "Hyponatremia"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "thiazide_worsens_hyponatremia", severity: "high"}]->(c);
MERGE (:Medication {name: "Losartan"});
MERGE (:Condition {name: "Hyperkalemia"});
MATCH (m:Medication {name: "Losartan"}) MATCH (c:Condition {name: "Hyperkalemia"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "ARB_raises_serum_potassium", severity: "high"}]->(c);
MERGE (:Medication {name: "Furosemide"});
MERGE (:Condition {name: "Hyponatremia"});
MATCH (m:Medication {name: "Furosemide"}) MATCH (c:Condition {name: "Hyponatremia"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "loop_diuretic_electrolyte_depletion", severity: "moderate"}]->(c);
MERGE (:Medication {name: "Morphine"});
MERGE (:Condition {name: "Chronic Kidney Disease"});
MATCH (m:Medication {name: "Morphine"}) MATCH (c:Condition {name: "Chronic Kidney Disease"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "active_metabolite_accumulation", severity: "high"}]->(c);
MERGE (:Medication {name: "Gabapentin"});
MERGE (:Condition {name: "Chronic Kidney Disease"});
MATCH (m:Medication {name: "Gabapentin"}) MATCH (c:Condition {name: "Chronic Kidney Disease"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "requires_renal_dose_adjustment", severity: "moderate"}]->(c);
MERGE (:Medication {name: "Aspirin"});
MERGE (:Condition {name: "Heart Failure"});
MATCH (m:Medication {name: "Aspirin"}) MATCH (c:Condition {name: "Heart Failure"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "fluid_retention_worsens_heart_failure", severity: "moderate"}]->(c);
MERGE (:Medication {name: "Metoprolol"});
MERGE (:Condition {name: "Asthma"});
MATCH (m:Medication {name: "Metoprolol"}) MATCH (c:Condition {name: "Asthma"}) MERGE (m)-[:CONTRAINDICATED_FOR {reason: "beta_blockade_induces_bronchospasm", severity: "high"}]->(c);

// Known adverse reactions
MERGE (:Medication {name: "Warfarin"});
MERGE (:Symptom {name: "palpitations"});
MATCH (m:Medication {name: "Warfarin"}) MATCH (s:Symptom {name: "palpitations"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "high", meddra_term: "Palpitation"}]->(s);
MERGE (:Medication {name: "Warfarin"});
MERGE (:Symptom {name: "confusion"});
MATCH (m:Medication {name: "Warfarin"}) MATCH (s:Symptom {name: "confusion"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "high", meddra_term: "Confusion"}]->(s);
MERGE (:Medication {name: "Lisinopril"});
MERGE (:Symptom {name: "cough"});
MATCH (m:Medication {name: "Lisinopril"}) MATCH (s:Symptom {name: "cough"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Cough"}]->(s);
MERGE (:Medication {name: "Lisinopril"});
MERGE (:Symptom {name: "dizziness"});
MATCH (m:Medication {name: "Lisinopril"}) MATCH (s:Symptom {name: "dizziness"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Dizziness"}]->(s);
MERGE (:Medication {name: "Atorvastatin"});
MERGE (:Symptom {name: "fatigue"});
MATCH (m:Medication {name: "Atorvastatin"}) MATCH (s:Symptom {name: "fatigue"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Fatigue"}]->(s);
MERGE (:Medication {name: "Atorvastatin"});
MERGE (:Symptom {name: "leg cramps"});
MATCH (m:Medication {name: "Atorvastatin"}) MATCH (s:Symptom {name: "leg cramps"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Myalgia"}]->(s);
MERGE (:Medication {name: "Amoxicillin"});
MERGE (:Symptom {name: "swelling"});
MATCH (m:Medication {name: "Amoxicillin"}) MATCH (s:Symptom {name: "swelling"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "high", meddra_term: "Angioedema"}]->(s);
MERGE (:Medication {name: "Amoxicillin"});
MERGE (:Symptom {name: "shortness of breath"});
MATCH (m:Medication {name: "Amoxicillin"}) MATCH (s:Symptom {name: "shortness of breath"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "high", meddra_term: "Dyspnoea"}]->(s);
MERGE (:Medication {name: "Metformin"});
MERGE (:Symptom {name: "nausea"});
MATCH (m:Medication {name: "Metformin"}) MATCH (s:Symptom {name: "nausea"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Nausea"}]->(s);
MERGE (:Medication {name: "Metformin"});
MERGE (:Symptom {name: "vomiting"});
MATCH (m:Medication {name: "Metformin"}) MATCH (s:Symptom {name: "vomiting"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Vomiting"}]->(s);
MERGE (:Medication {name: "Metoprolol"});
MERGE (:Symptom {name: "dizziness"});
MATCH (m:Medication {name: "Metoprolol"}) MATCH (s:Symptom {name: "dizziness"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Dizziness"}]->(s);
MERGE (:Medication {name: "Metoprolol"});
MERGE (:Symptom {name: "fatigue"});
MATCH (m:Medication {name: "Metoprolol"}) MATCH (s:Symptom {name: "fatigue"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Fatigue"}]->(s);
MERGE (:Medication {name: "Albuterol"});
MERGE (:Symptom {name: "palpitations"});
MATCH (m:Medication {name: "Albuterol"}) MATCH (s:Symptom {name: "palpitations"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Palpitation"}]->(s);
MERGE (:Medication {name: "Albuterol"});
MERGE (:Symptom {name: "chest pain"});
MATCH (m:Medication {name: "Albuterol"}) MATCH (s:Symptom {name: "chest pain"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Chest Pain"}]->(s);
MERGE (:Medication {name: "Levothyroxine"});
MERGE (:Symptom {name: "palpitations"});
MATCH (m:Medication {name: "Levothyroxine"}) MATCH (s:Symptom {name: "palpitations"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Palpitation"}]->(s);
MERGE (:Medication {name: "Levothyroxine"});
MERGE (:Symptom {name: "weight loss"});
MATCH (m:Medication {name: "Levothyroxine"}) MATCH (s:Symptom {name: "weight loss"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Weight loss"}]->(s);
MERGE (:Medication {name: "Morphine"});
MERGE (:Symptom {name: "dizziness"});
MATCH (m:Medication {name: "Morphine"}) MATCH (s:Symptom {name: "dizziness"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Dizziness"}]->(s);
MERGE (:Medication {name: "Morphine"});
MERGE (:Symptom {name: "nausea"});
MATCH (m:Medication {name: "Morphine"}) MATCH (s:Symptom {name: "nausea"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Nausea"}]->(s);
MERGE (:Medication {name: "Sertraline"});
MERGE (:Symptom {name: "headache"});
MATCH (m:Medication {name: "Sertraline"}) MATCH (s:Symptom {name: "headache"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Headache"}]->(s);
MERGE (:Medication {name: "Sertraline"});
MERGE (:Symptom {name: "nausea"});
MATCH (m:Medication {name: "Sertraline"}) MATCH (s:Symptom {name: "nausea"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Nausea"}]->(s);
MERGE (:Medication {name: "Azithromycin"});
MERGE (:Symptom {name: "nausea"});
MATCH (m:Medication {name: "Azithromycin"}) MATCH (s:Symptom {name: "nausea"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Nausea"}]->(s);
MERGE (:Medication {name: "Azithromycin"});
MERGE (:Symptom {name: "shortness of breath"});
MATCH (m:Medication {name: "Azithromycin"}) MATCH (s:Symptom {name: "shortness of breath"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "high", meddra_term: "QT Prolongation/Dyspnoea"}]->(s);
MERGE (:Medication {name: "Amlodipine"});
MERGE (:Symptom {name: "swelling"});
MATCH (m:Medication {name: "Amlodipine"}) MATCH (s:Symptom {name: "swelling"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Peripheral Oedema"}]->(s);
MERGE (:Medication {name: "Amlodipine"});
MERGE (:Symptom {name: "dizziness"});
MATCH (m:Medication {name: "Amlodipine"}) MATCH (s:Symptom {name: "dizziness"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Dizziness"}]->(s);
MERGE (:Medication {name: "Omeprazole"});
MERGE (:Symptom {name: "headache"});
MATCH (m:Medication {name: "Omeprazole"}) MATCH (s:Symptom {name: "headache"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Headache"}]->(s);
MERGE (:Medication {name: "Omeprazole"});
MERGE (:Symptom {name: "nausea"});
MATCH (m:Medication {name: "Omeprazole"}) MATCH (s:Symptom {name: "nausea"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Nausea"}]->(s);
MERGE (:Medication {name: "Losartan"});
MERGE (:Symptom {name: "dizziness"});
MATCH (m:Medication {name: "Losartan"}) MATCH (s:Symptom {name: "dizziness"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Dizziness"}]->(s);
MERGE (:Medication {name: "Losartan"});
MERGE (:Symptom {name: "headache"});
MATCH (m:Medication {name: "Losartan"}) MATCH (s:Symptom {name: "headache"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Headache"}]->(s);
MERGE (:Medication {name: "Gabapentin"});
MERGE (:Symptom {name: "dizziness"});
MATCH (m:Medication {name: "Gabapentin"}) MATCH (s:Symptom {name: "dizziness"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Dizziness"}]->(s);
MERGE (:Medication {name: "Gabapentin"});
MERGE (:Symptom {name: "confusion"});
MATCH (m:Medication {name: "Gabapentin"}) MATCH (s:Symptom {name: "confusion"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Confusion"}]->(s);
MERGE (:Medication {name: "Gabapentin"});
MERGE (:Symptom {name: "blurred vision"});
MATCH (m:Medication {name: "Gabapentin"}) MATCH (s:Symptom {name: "blurred vision"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Vision Blurred"}]->(s);
MERGE (:Medication {name: "Hydrochlorothiazide"});
MERGE (:Symptom {name: "dizziness"});
MATCH (m:Medication {name: "Hydrochlorothiazide"}) MATCH (s:Symptom {name: "dizziness"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Orthostatic Hypotension"}]->(s);
MERGE (:Medication {name: "Hydrochlorothiazide"});
MERGE (:Symptom {name: "leg cramps"});
MATCH (m:Medication {name: "Hydrochlorothiazide"}) MATCH (s:Symptom {name: "leg cramps"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Hypokalaemia/Muscle Cramp"}]->(s);
MERGE (:Medication {name: "Prednisone"});
MERGE (:Symptom {name: "weight loss"});
MATCH (m:Medication {name: "Prednisone"}) MATCH (s:Symptom {name: "weight loss"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Weight Decreased"}]->(s);
MERGE (:Medication {name: "Prednisone"});
MERGE (:Symptom {name: "fatigue"});
MATCH (m:Medication {name: "Prednisone"}) MATCH (s:Symptom {name: "fatigue"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Fatigue"}]->(s);
MERGE (:Medication {name: "Prednisone"});
MERGE (:Symptom {name: "night sweats"});
MATCH (m:Medication {name: "Prednisone"}) MATCH (s:Symptom {name: "night sweats"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Night Sweats"}]->(s);
MERGE (:Medication {name: "Heparin"});
MERGE (:Symptom {name: "shortness of breath"});
MATCH (m:Medication {name: "Heparin"}) MATCH (s:Symptom {name: "shortness of breath"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "high", meddra_term: "Dyspnoea"}]->(s);
MERGE (:Medication {name: "Heparin"});
MERGE (:Symptom {name: "swelling"});
MATCH (m:Medication {name: "Heparin"}) MATCH (s:Symptom {name: "swelling"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "high", meddra_term: "Heparin-Induced Thrombocytopenia"}]->(s);
MERGE (:Medication {name: "Insulin Glargine"});
MERGE (:Symptom {name: "confusion"});
MATCH (m:Medication {name: "Insulin Glargine"}) MATCH (s:Symptom {name: "confusion"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "high", meddra_term: "Hypoglycaemia/Confusion"}]->(s);
MERGE (:Medication {name: "Insulin Glargine"});
MERGE (:Symptom {name: "dizziness"});
MATCH (m:Medication {name: "Insulin Glargine"}) MATCH (s:Symptom {name: "dizziness"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Hypoglycaemia/Dizziness"}]->(s);
MERGE (:Medication {name: "Furosemide"});
MERGE (:Symptom {name: "dizziness"});
MATCH (m:Medication {name: "Furosemide"}) MATCH (s:Symptom {name: "dizziness"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Hypotension/Dizziness"}]->(s);
MERGE (:Medication {name: "Furosemide"});
MERGE (:Symptom {name: "leg cramps"});
MATCH (m:Medication {name: "Furosemide"}) MATCH (s:Symptom {name: "leg cramps"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Hypokalaemia/Muscle Cramp"}]->(s);
MERGE (:Medication {name: "Clopidogrel"});
MERGE (:Symptom {name: "headache"});
MATCH (m:Medication {name: "Clopidogrel"}) MATCH (s:Symptom {name: "headache"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Headache"}]->(s);
MERGE (:Medication {name: "Clopidogrel"});
MERGE (:Symptom {name: "dizziness"});
MATCH (m:Medication {name: "Clopidogrel"}) MATCH (s:Symptom {name: "dizziness"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Dizziness"}]->(s);
MERGE (:Medication {name: "Dexamethasone"});
MERGE (:Symptom {name: "fatigue"});
MATCH (m:Medication {name: "Dexamethasone"}) MATCH (s:Symptom {name: "fatigue"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "low", meddra_term: "Fatigue"}]->(s);
MERGE (:Medication {name: "Dexamethasone"});
MERGE (:Symptom {name: "weight loss"});
MATCH (m:Medication {name: "Dexamethasone"}) MATCH (s:Symptom {name: "weight loss"}) MERGE (m)-[:HAS_KNOWN_REACTION {severity: "moderate", meddra_term: "Weight Decreased"}]->(s);
