networkPolicies:
  enabled: true
rag-api:
  enabled: true
provider-web:
  enabled: true
flink:
  enabled: true
mlflow:
  enabled: true
kafka:
  enabled: false
neo4j:
  enabled: false
qdrant:
  enabled: false
ollama:
  enabled: false