apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      enableServiceLinks: false
      containers:
      - name: neo4j
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt
        env:
        - name: NEO4J_AUTH
          value: "neo4j/{{ .Values.auth.password }}"
        - name: NEO4J_PLUGINS
          value: {{ .Values.plugins | toJson | quote }}
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: neo4j-data
        {{- else }}
        emptyDir: {}
        {{- end }}
---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  type: {{ .Values.service.type }}
  selector:
    app: neo4j
  ports:
  - name: http
    port: 7474
    targetPort: http
  - name: bolt
    port: 7687
    targetPort: bolt
