enabled: false
image:
  repository: ollama/ollama
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 4000m
    memory: 8Gi