{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: rag-api-secrets
  labels:
    {{- include "rag-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
