FROM nginx:alpine
COPY webapp/nginx.conf /etc/nginx/conf.d/default.conf
COPY webapp/index.html /usr/share/nginx/html/index.html
COPY webapp/app.js /usr/share/nginx/html/app.js
COPY webapp/styles.css /usr/share/nginx/html/styles.css
